### ISSUE TITLE
Problem displaying rich text in Content field?

### ISSUE THREAD

**Issue by shepaldo** [Sterc/seosuite#4]
SEO Suite 2.0.1 seems to break the display of the rich text Content field? MODX is 2.8.1 and editor is TinyMCE 4.3.4-pl.
Removing SEO Suite restores the correct rich text display.

![With SEO Suite](https://user-images.githubusercontent.com/718308/105384107-bf5df900-5c09-11eb-8c5a-25bf9fd7da85.jpg)
![Without SEO Suite](https://user-images.githubusercontent.com/718308/105384120-c258e980-5c09-11eb-935f-11fcb71df310.jpg)

**Comment by gpsietzema** [comment]
Thanks for the report. Any ideas what's happening? Is all styling gone somehow? Or are we failing to close a div or something?

**Comment by shepaldo** [comment]
Yes, all styling seems to be gone, except that the text is wrapped by a single paragraph element.
![html](https://user-images.githubusercontent.com/718308/105404273-b1b46d80-5c21-11eb-9f3d-4bce81d6a295.jpg)

**Comment by shepaldo** [comment]
The error log in MODX has a long list of these:

[2021-01-21 19:44:52] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:44:52] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:46:58] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:46:58] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:46:58] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:46:58] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:47:16] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:47:16] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:47:53] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:47:53] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:49:41] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-01-21 19:49:41] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
/

**Comment by Oetzie** [comment]
@shepaldo A easy fix would be to remove line 393 in https://github.com/Sterc/seosuite/blob/development/assets/components/seosuite/js/mgr/resource/resource.tab_meta.js.

We will create a fix/new release asap.

**Comment by Oetzie** [comment]
@shepaldo I pushed a fix for this issue, https://github.com/Sterc/seosuite/commit/7216bfa473b525ce78a00e01b23370c768b5c8c1. An other developer will create a new release

**Comment by sdrenth** [comment]
@shepaldo I've released v2.0.2 which resolves this issue.

**Comment by shepaldo** [comment]
...still get the same problem with v2.0.2 I'm afraid (the client isn't using Redactor)...

[2021-01-22 12:06:34] (ERROR @ /home/sites/14b/b/b58ac641d6/public_html/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given

**Comment by shepaldo** [comment]
> @shepaldo A easy fix would be to remove line 393 in https://github.com/Sterc/seosuite/blob/development/assets/components/seosuite/js/mgr/resource/resource.tab_meta.js.
> 
> We will create a fix/new release asap.

Only applies if using Redactor?

**Comment by Oetzie** [comment]
@shepaldo no, should also be fixed for TinyMCE or other WYSIWYG editors. Did you do a hard page refresh, I quess the `resource.tab_meta.js` file is cached by the browser or something.

We did not fixed the PHP error in this release.

**Comment by shepaldo** [comment]
AHAH! Hard refresh & clearing the cache from within the MODX Manager didn't work after upgrading, but emptying the cache folder manually fixed it - many thanks!!!
![Screenshot 2021-01-22 at 13 22 22](https://user-images.githubusercontent.com/718308/105496554-89764e80-5cb5-11eb-803c-20ca9fba7b88.jpg)
![Screenshot 2021-01-22 at 13 25 00](https://user-images.githubusercontent.com/718308/105496573-9004c600-5cb5-11eb-891e-aea21867b114.jpg)
